# ~/.config/hypr/hypridle.conf
general {
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
    lock_cmd = pidof hyprlock || hyprlock
}

listener {
    timeout = 600
    on-timeout = brightnessctl -s set 30%
    on-resume = brightnessctl -r
}

listener {
    timeout = 900
    on-timeout = hyprlock
}

listener {
    timeout = 1800
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
