# ~/.config/btop/btop.conf — arch-hypr-deck
theme_name = "TTY"
color_theme = "tty"
force_tty = 0
presets = "cpu:1:default,proc:0:default cpu:0:default,mem:0:default,net:0:default cpu:0:block,net:0:tty"
vmem = True
proc_sorting = cpu
proc_tree = True
show_battery = True
selected_battery = "BAT0"
clock_format = "%H:%M"
base_10_sizes = False
show_cpu_watts = True
draw_graph = 1
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 1500
temp_scale = celsius
